---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: 3.3.1
serverless_language: ''
polling_url: "https://api.sleeper.app/v1/league/{{league_id}}/matchups/{{week}}\r\nhttps://api.sleeper.app/v1/league/{{league_id}}/rosters\r\nhttps://api.sleeper.app/v1/league/{{league_id}}/users\r\nhttps://api.sleeper.app/v1/state/nfl"
polling_headers: ''
polling_body: ''
id: 140922
oauth_enabled: 'false'
oauth_pkce_enabled: 'no'
oauth_authorize_url: ''
oauth_token_url: ''
oauth_scopes: ''
oauth_scope_separator: ''
oauth_refresh_url: ''
oauth_auth_params: ''
oauth_token_headers: ''
oauth_token_site: ''
oauth_token_params: ''
oauth_token_request_auth_method: ''
oauth_body_format: ''
oauth_token_response_metadata: ''
oauth_authorization_method: ''
oauth_refresh_params: ''
oauth_token_field_name: ''
oauth_expiry_field_name: ''
oauth_expiry_strategy: ''
oauth_fixed_expiry_ms: ''
custom_fields:
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  description: Display your sleeper league matchups by week [Now built on Framework 3 and optimized for TRMNL X]
  help_text: TRMNL X Ready
  github_url: https://github.com/bnussbau/trmnl-sleeper-matchups
  learn_more_url: https://github.com/bnussbau/trmnl-sleeper-matchups/blob/main/README.md
  email_address: trmnl@benjaminnussbaum.at
- keyname: league_id
  field_type: string
  name: League ID
  help_text: Get your League ID <a href="https://sleeper-league-finder.divine-wood-7de9.workers.dev/" class="underline" target="_blank">here</a>.
- keyname: week
  field_type: number
  name: Week
  description: Sorry, there isn't currently a way to automatically detect the current week.
- keyname: reminder
  field_type: select
  options:
  - 'Yes'
  - 'No'
  default: 'yes'
  name: Week Reminder
  description: Would you like to be reminded to update the week in plugin settings?
- keyname: league_name
  field_type: string
  optional: true
  name: League Name (optional)
  description: If you want to display the league name in the title bar.
name: 'Sleeper: Matchups'
description: Sleeper league matchups by week
refresh_interval: 60
